[project]
name = "python-advanced-file-processing"
version = "0.1.0"
authors = [
    {name = "Piotr OpaÅ‚a", email = "opalapj@gmail.com"},
]
license = {text = "MIT"}
dependencies = ["SQLAlchemy>=2.0.44"]
requires-python = "==3.13.*"

[tool.pdm]
distribution = false
